### ISSUE TITLE
Close parrot file after reading into GIF

### ISSUE THREAD

**Issue by fharding1** [fharding1/ppaas#2]
So it's not open for the entire life of the server for no reason.

**Comment by tenpaiyomi** [comment]
Looking into this one!

**Comment by tenpaiyomi** [comment]
@fharding1 I've addressed this issue with the pull request [here](https://github.com/fharding1/ppaas/pull/5).

If there are any questions or concerns, please feel free to let me know.  I'm not super experienced with Golang yet, so this has been a bit of a learning experience for me with the `defer` functionality.  Thank you!

**Comment by fharding1** [comment]
@tenpaiyomi awesome, replied! Glad to know you learned something from contributing :+1:
